<?php
namespace ThirstyAffiliates_Pro\Helpers;

use ThirstyAffiliates_Pro\Abstracts\Abstract_Main_Plugin_Class;

if ( !defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

/**
 * Model that houses all the plugin constants.
 * Note as much as possible, we need to make this class succinct as the only purpose of this is to house all the constants that is utilized by the plugin.
 * Therefore we omit class member comments and minimize comments as much as possible.
 * In fact the only verbouse comment here is this comment you are reading right now.
 * And guess what, it just got worse coz now this comment takes 5 lines instead of 3.
 *
 * @since 1.0.0
 */
class Plugin_Constants {

    /*
    |--------------------------------------------------------------------------
    | Class Properties
    |--------------------------------------------------------------------------
    */

    private static $_instance;

    // Plugin configuration constants
    const TOKEN               = 'tap';
    const INSTALLED_VERSION   = 'tap_installed_version';
    const VERSION             = '1.3.3';
    const TEXT_DOMAIN         = 'thirstyaffiliates-pro';
    const THEME_TEMPLATE_PATH = 'thirstyaffiliates-pro';
    const META_DATA_PREFIX    = '_ta_';

    // SLMW
    const PLUGIN_SITE_URL               = 'https://thirstyaffiliates.com';
    const LICENSE_ACTIVATION_URL        = 'https://thirstyaffiliates.com/wp-admin/admin-ajax.php?action=slmw_activate_license';
    const UPDATE_DATA_URL               = 'https://thirstyaffiliates.com/wp-admin/admin-ajax.php?action=slmw_get_update_data';
    const STATIC_PING_FILE              = 'https://thirstyaffiliates.com/TAP.json';
    const CRON_PING_NEW_VERSION         = 'tap_cron_new_version'; // TODO: Remove on future versions
    const OPTION_ACTIVATION_EMAIL       = 'tap_slmw_activation_email';
    const OPTION_LICENSE_KEY            = 'tap_slmw_license_key';
    const OPTION_LICENSE_ACTIVATED      = 'tap_license_activated';
    const OPTION_UPDATE_DATA            = 'tap_option_update_data'; // Option that holds retrieved software product update data
    const OPTION_RETRIEVING_UPDATE_DATA = 'tap_option_retrieving_update_data';

    // CPT Taxonomy constants
    const AFFILIATE_LINKS_CPT    = 'thirstylink';
    const AFFILIATE_LINKS_TAX    = 'thirstylink-category';
    const DEFAULT_LINK_CATEGORY  = 'Uncategorized';
    const EVENT_NOTIFICATION_TAX = 'tap-event-notification';

    // CRON
    const LINK_HEALTH_CHECKER    = 'tap_link_health_checker';

    // Amazon Module
    const LAST_USED_SEARCH_ENDPOINT   = 'tap_last_used_search_endpoint';
    const AMAZON_TABLE_COLUMNS        = 'tap_amazon_table_columns';
    const AMAZON_API_VERSION          = '2013-08-01';
    const AMAZON_API_SERVICE          = 'AWSECommerceService';
    const AMAZON_API_OPERATION        = 'ItemSearch';
    const AMAZON_API_RESPONSE_GROUP   = 'ItemAttributes,Offers,Images,SalesRank'; // http://docs.aws.amazon.com/AWSECommerceService/latest/DG/CHAP_ResponseGroupsList.html
    const AMAZON_GENERATED_TRANSIENTS = 'tap_amazon_generated_transient'; // Option that holds the keys of all transients generated by amazon module

    // URL Shortener
    const BITLY_API_URL             = 'https://api-ssl.bitly.com/v3/';
    const GOOGL_SHORTENER_URL       = 'https://www.googleapis.com/urlshortener/v1/url';
    const FIREBASE_DL_SHORTENER_URL = 'https://firebasedynamiclinks.googleapis.com/v1/shortLinks';

    // Settings Constants

    // DB Tables
    const LINK_CLICK_DB      = 'ta_link_clicks';
    const LINK_CLICK_META_DB = 'ta_link_clicks_meta';

    // Help Section
    const CLEAN_UP_PLUGIN_OPTIONS = 'tap_clean_up_plugin_options';




    /*
    |--------------------------------------------------------------------------
    | Class Methods
    |--------------------------------------------------------------------------
    */

    public function __construct( Abstract_Main_Plugin_Class $main_plugin ) {

        // Path constants
        $this->_MAIN_PLUGIN_FILE_PATH = WP_PLUGIN_DIR . DIRECTORY_SEPARATOR . 'thirstyaffiliates-pro' . DIRECTORY_SEPARATOR . 'thirstyaffiliates-pro.php';
        $this->_PLUGIN_DIR_PATH       = plugin_dir_path( $this->_MAIN_PLUGIN_FILE_PATH );
        $this->_PLUGIN_DIR_URL        = plugin_dir_url( $this->_MAIN_PLUGIN_FILE_PATH );
        $this->_PLUGIN_DIRNAME        = plugin_basename( dirname( $this->_MAIN_PLUGIN_FILE_PATH ) );
        $this->_PLUGIN_BASENAME       = plugin_basename( $this->_MAIN_PLUGIN_FILE_PATH );

        $this->_CSS_ROOT_URL          = $this->_PLUGIN_DIR_URL . 'css/';
        $this->_IMAGES_ROOT_URL       = $this->_PLUGIN_DIR_URL . 'images/';
        $this->_JS_ROOT_URL           = $this->_PLUGIN_DIR_URL . 'js/';

        $this->_VIEWS_ROOT_PATH       = $this->_PLUGIN_DIR_PATH . 'views/';
        $this->_TEMPLATES_ROOT_PATH   = $this->_PLUGIN_DIR_PATH . 'templates/';
        $this->_LOGS_ROOT_PATH        = $this->_PLUGIN_DIR_PATH . 'logs/';
        $this->_MESC_ROOT_PATH        = $this->_PLUGIN_DIR_PATH . 'mesc/';

        $this->_UPLOADS_DIR           = wp_upload_dir();
        $this->_TA_UPLOADS_DIR        = trailingslashit( $this->_UPLOADS_DIR[ 'basedir' ] ) . 'thirstyaffilates/';

        $main_plugin->add_to_public_helpers( $this );

    }

    public static function get_instance( Abstract_Main_Plugin_Class $main_plugin ) {

        if ( !self::$_instance instanceof self )
            self::$_instance = new self( $main_plugin );

        return self::$_instance;

    }

    public function MAIN_PLUGIN_FILE_PATH() {
        return $this->_MAIN_PLUGIN_FILE_PATH;
    }

    public function PLUGIN_DIR_PATH() {
        return $this->_PLUGIN_DIR_PATH;
    }

    public function PLUGIN_DIR_URL() {
        return $this->_PLUGIN_DIR_URL;
    }

    public function PLUGIN_DIRNAME() {
        return $this->_PLUGIN_DIRNAME;
    }

    public function PLUGIN_BASENAME() {
        return $this->_PLUGIN_BASENAME;
    }

    public function CSS_ROOT_URL() {
        return $this->_CSS_ROOT_URL;
    }

    public function IMAGES_ROOT_URL() {
        return $this->_IMAGES_ROOT_URL;
    }

    public function JS_ROOT_URL() {
        return $this->_JS_ROOT_URL;
    }

    public function VIEWS_ROOT_PATH() {
        return $this->_VIEWS_ROOT_PATH;
    }

    public function TEMPLATES_ROOT_PATH() {
        return $this->_TEMPLATES_ROOT_PATH;
    }

    public function LOGS_ROOT_PATH() {
        return $this->_LOGS_ROOT_PATH;
    }

    public function MESC_ROOT_PATH() {
        return $this->_MESC_ROOT_PATH;
    }

    public function TA_UPLOADS_DIR() {
        return $this->_TA_UPLOADS_DIR;
    }

    // Amazon Module

    // Reference : http://docs.aws.amazon.com/AWSECommerceService/latest/DG/AnatomyOfaRESTRequest.html
    public function AMAZON_SEARCH_COUNTRIES() {

        return array(
                    "US" => __( "United States" , "thirstyaffiliates-pro" ),
                    "CA" => __( "Canada" , "thirstyaffiliates-pro" ),
                    "CN" => __( "China" , "thirstyaffiliates-pro" ),
                    "DE" => __( "Germany" , "thirstyaffiliates-pro" ),
                    "ES" => __( "Spain" , "thirstyaffiliates-pro" ),
                    "FR" => __( "France" , "thirstyaffiliates-pro" ),
                    "IN" => __( "India" , "thirstyaffiliates-pro" ),
                    "IT" => __( "Italy" , "thirstyaffiliates-pro" ),
                    "JP" => __( "Japan" , "thirstyaffiliates-pro" ),
                    "MX" => __( "Mexico" , "thirstyaffiliates-pro" ),
                    "UK" => __( "United Kingdom" , "thirstyaffiliates-pro" ),
                    "BR" => __( "Brazil" , "thirstyaffiliates-pro" )
                );

    }

    // Reference : http://docs.aws.amazon.com/AWSECommerceService/latest/DG/localevalues.html
    public function AMAZON_SEARCH_INDEX() {

        return array(
                    "US" => array(
                                "All"                => __( "-- All Departments --" , "thirstyaffiliates-pro" ),
                                "Appliances"         => __( "Appliances" , "thirstyaffiliates-pro" ),
                                "ArtsAndCrafts"      => __( "Arts, Crafts & Sewing" , "thirstyaffiliates-pro" ),
                                "Automotive"         => __( "Automotive" , "thirstyaffiliates-pro" ),
                                "Baby"               => __( "Baby" , "thirstyaffiliates-pro" ),
                                "Beauty"             => __( "Beauty" , "thirstyaffiliates-pro" ),
                                "Blended"            => __( "Blended" , "thirstyaffiliates-pro" ),
                                "Books"              => __( "Books" , "thirstyaffiliates-pro" ),
                                "Collectibles"       => __( "Collectibles & Fine Arts" , "thirstyaffiliates-pro" ),
                                "Electronics"        => __( "Electronics" , "thirstyaffiliates-pro" ),
                                "Fashion"            => __( "Clothing, Shoes & Jewelry" , "thirstyaffiliates-pro" ),
                                "FashionBaby"        => __( "Clothing, Shoes & Jewelry - Baby" , "thirstyaffiliates-pro" ),
                                "FashionBoys"        => __( "Clothing, Shoes & Jewelry - Boys" , "thirstyaffiliates-pro" ),
                                "FashionGirls"       => __( "Clothing, Shoes & Jewelry - Girls" , "thirstyaffiliates-pro" ),
                                "FashionMen"         => __( "Clothing, Shoes & Jewelry - Men" , "thirstyaffiliates-pro" ),
                                "FashionWomen"       => __( "Clothing, Shoes & Jewelry - Women" , "thirstyaffiliates-pro" ),
                                "GiftCards"          => __( "Gift Cards" , "thirstyaffiliates-pro" ),
                                "Grocery"            => __( "Grocery & Gourmet Food" , "thirstyaffiliates-pro" ),
                                "Handmade"           => __( "Handmade" , "thirstyaffiliates-pro" ),
                                "HealthPersonalCare" => __( "Health & Personal Care" , "thirstyaffiliates-pro" ),
                                "HomeGarden"         => __( "Home & Garden" , "thirstyaffiliates-pro" ),
                                "Industrial"         => __( "Industrial & Scientific" , "thirstyaffiliates-pro" ),
                                "LawnAndGarden"      => __( "Patio, Lawn & Garden" , "thirstyaffiliates-pro" ),
                                "Luggage"            => __( "Luggage & Travel Gear" , "thirstyaffiliates-pro" ),
                                "Magazines"          => __( "Magazine Subscriptions" , "thirstyaffiliates-pro" ),
                                "Marketplace"        => __( "Marketplace" , "thirstyaffiliates-pro" ),
                                "Merchants"          => __( "Merchants" , "thirstyaffiliates-pro" ),
                                "MobileApps"         => __( "Apps & Games" , "thirstyaffiliates-pro" ),
                                "Movies"             => __( "Movies & TV" , "thirstyaffiliates-pro" ),
                                "MP3Downloads"       => __( "Digital Music" , "thirstyaffiliates-pro" ),
                                "Music"              => __( "CDs & Vinyl" , "thirstyaffiliates-pro" ),
                                "MusicalInstruments" => __( "Musical Instruments" , "thirstyaffiliates-pro" ),
                                "OfficeProducts"     => __( "Office Products" , "thirstyaffiliates-pro" ),
                                "Pantry"             => __( "Prime Pantry" , "thirstyaffiliates-pro" ),
                                "PCHardware"         => __( "Computers" , "thirstyaffiliates-pro" ),
                                "PetSupplies"        => __( "Pet Supplies" , "thirstyaffiliates-pro" ),
                                "Software"           => __( "Software" , "thirstyaffiliates-pro" ),
                                "SportingGoods"      => __( "Sports & Outdoors" , "thirstyaffiliates-pro" ),
                                "Tools"              => __( "Tools & Home Improvement" , "thirstyaffiliates-pro" ),
                                "Toys"               => __( "Toys & Games" , "thirstyaffiliates-pro" ),
                                "UnboxVideo"         => __( "Amazon Instant Video" , "thirstyaffiliates-pro" ),
                                "Vehicles"           => __( "Vehicles" , "thirstyaffiliates-pro" ),
                                "VideoGames"         => __( "VideoGames" , "thirstyaffiliates-pro" ),
                                "Wine"               => __( "Wine" , "thirstyaffiliates-pro" ),
                                "Wireless"           => __( "Cell Phones & Accessories" , "thirstyaffiliates-pro" )
                            ),
                    "CA" => array(
                                "All"                => __( "-- All Departments --" , "thirstyaffiliates-pro" ),
                                "Apparel"            => __( "Clothing & Accessories" , "thirstyaffiliates-pro" ),
                                "Automotive"         => __( "Automotive" , "thirstyaffiliates-pro" ),
                                "Baby"               => __( "Baby" , "thirstyaffiliates-pro" ),
                                "Beauty"             => __( "Beauty" , "thirstyaffiliates-pro" ),
                                "Blended"            => __( "Blended" , "thirstyaffiliates-pro" ),
                                "Books"              => __( "Books" , "thirstyaffiliates-pro" ),
                                "DVD"                => __( "Movies & TV" , "thirstyaffiliates-pro" ),
                                "DVD"                => __( "DVD" , "thirstyaffiliates-pro" ),
                                "Electronics"        => __( "Electronics" , "thirstyaffiliates-pro" ),
                                "GiftCards"          => __( "Gift Cards" , "thirstyaffiliates-pro" ),
                                "Grocery"            => __( "Grocery & Gourmet Food" , "thirstyaffiliates-pro" ),
                                "ForeignBooks"       => __( "Foreign Books" , "thirstyaffiliates-pro" ),
                                "HealthPersonalCare" => __( "Health & Personal Care" , "thirstyaffiliates-pro" ),
                                "Industrial"         => __( "Industrial & Scientific" , "thirstyaffiliates-pro" ),
                                "Jewelry"            => __( "Jewelry" , "thirstyaffiliates-pro" ),
                                "KindleStore"        => __( "Kindle Store" , "thirstyaffiliates-pro" ),
                                "Kitchen"            => __( "Home & Kitchen" , "thirstyaffiliates-pro" ),
                                "LawnAndGarden"      => __( "Patio, Lawn & Garden" , "thirstyaffiliates-pro" ),
                                "Luggage"            => __( "Luggage & Bags" , "thirstyaffiliates-pro" ),
                                "Marketplace"        => __( "Marketplace" , "thirstyaffiliates-pro" ),
                                "MobileApps"         => __( "Apps & Games" , "thirstyaffiliates-pro" ),
                                "Music"              => __( "Music" , "thirstyaffiliates-pro" ),
                                "MusicalInstruments" => __( "Musical Instruments, Stage & Studio" , "thirstyaffiliates-pro" ),
                                "OfficeProducts"     => __( "Office Products" , "thirstyaffiliates-pro" ),
                                "PetSupplies"        => __( "Pet Supplies" , "thirstyaffiliates-pro" ),
                                "Shoes"              => __( "Shoes & Handbags" , "thirstyaffiliates-pro" ),
                                "Software"           => __( "Software" , "thirstyaffiliates-pro" ),
                                "SportingGoods"      => __( "Sports & Outdoors" , "thirstyaffiliates-pro" ),
                                "Tools"              => __( "Tools & Home Improvement" , "thirstyaffiliates-pro" ),
                                "Toys"               => __( "Toys & Games" , "thirstyaffiliates-pro" ),
                                "VideoGames"         => __( "Video Games" , "thirstyaffiliates-pro" ),
                                "Watches"            => __( "Watches" , "thirstyaffiliates-pro" )
                            ),
                    "CN" => array(
                                "All"                => __( "-- All Departments --" , "thirstyaffiliates-pro" ),
                                "Apparel"            => __( "Clothing" , "thirstyaffiliates-pro" ),
                                "Appliances"         => __( "Large Appliances" , "thirstyaffiliates-pro" ),
                                "Automotive"         => __( "Auto Accessories" , "thirstyaffiliates-pro" ),
                                "Baby"               => __( "Baby Products" , "thirstyaffiliates-pro" ),
                                "Beauty"             => __( "Beauty Products" , "thirstyaffiliates-pro" ),
                                "Books"              => __( "Books" , "thirstyaffiliates-pro" ),
                                "Electronics"        => __( "Electronics" , "thirstyaffiliates-pro" ),
                                "GiftCards"          => __( "Gift Cards" , "thirstyaffiliates-pro" ),
                                "Grocery"            => __( "Grocery" , "thirstyaffiliates-pro" ),
                                "HealthPersonalCare" => __( "Health Care" , "thirstyaffiliates-pro" ),
                                "Home"               => __( "Home" , "thirstyaffiliates-pro" ),
                                "HomeImprovement"    => __( "home Renovation" , "thirstyaffiliates-pro" ),
                                "Jewelry"            => __( "Jewelry" , "thirstyaffiliates-pro" ),
                                "KindleStore"        => __( "Kindle Store" , "thirstyaffiliates-pro" ),
                                "Kitchen"            => __( "Kitchenware" , "thirstyaffiliates-pro" ),
                                "MobileApps"         => __( "Applications and Games" , "thirstyaffiliates-pro" ),
                                "Music"              => __( "Music" , "thirstyaffiliates-pro" ),
                                "MusicalInstruments" => __( "Musical Instruments" , "thirstyaffiliates-pro" ),
                                "OfficeProducts"     => __( "Office Supplies" , "thirstyaffiliates-pro" ),
                                "PCHardware"         => __( "Computer / IT" , "thirstyaffiliates-pro" ),
                                "PetSupplies"        => __( "Pet Supplies" , "thirstyaffiliates-pro" ),
                                "Photo"              => __( "Photography" , "thirstyaffiliates-pro" ),
                                "Shoes"              => __( "Footwear" , "thirstyaffiliates-pro" ),
                                "Software"           => __( "Software" , "thirstyaffiliates-pro" ),
                                "SportingGoods"      => __( "Sports and Outdoors" , "thirstyaffiliates-pro" ),
                                "Toys"               => __( "Toys" , "thirstyaffiliates-pro" ),
                                "Video"              => __( "Video" , "thirstyaffiliates-pro" ),
                                "VideoGames"         => __( "Game Entertainment" , "thirstyaffiliates-pro" ),
                                "Watches"            => __( "Watches" , "thirstyaffiliates-pro" )
                            ),
                    "DE" => array(
                                "All"                => __( "-- All Departments --" , "thirstyaffiliates-pro" ),
                                "Apparel"            => __( "Clothing" , "thirstyaffiliates-pro" ),
                                "Appliances"         => __( "Electrical Appliances" , "thirstyaffiliates-pro" ),
                                "Automotive"         => __( "Automotive" , "thirstyaffiliates-pro" ),
                                "Baby"               => __( "Baby" , "thirstyaffiliates-pro" ),
                                "Beauty"             => __( "Beauty" , "thirstyaffiliates-pro" ),
                                "Blended"            => __( "Blended" , "thirstyaffiliates-pro" ),
                                "Books"              => __( "Books" , "thirstyaffiliates-pro" ),
                                "Classical"          => __( "Classical" , "thirstyaffiliates-pro" ),
                                "DVD"                => __( "DVD & Blu-ray" , "thirstyaffiliates-pro" ),
                                "Electronics"        => __( "Electronics" , "thirstyaffiliates-pro" ),
                                "ForeignBooks"       => __( "Foreign Books" , "thirstyaffiliates-pro" ),
                                "GiftCards"          => __( "Gift Cards" , "thirstyaffiliates-pro" ),
                                "Grocery"            => __( "Food and Drink" , "thirstyaffiliates-pro" ),
                                "Handmade"           => __( "Handmade" , "thirstyaffiliates-pro" ),
                                "HealthPersonalCare" => __( "Health & Personal Care" , "thirstyaffiliates-pro" ),
                                "HomeGarden"         => __( "Home Garden" , "thirstyaffiliates-pro" ),
                                "Industrial"         => __( "Industrial & Scientific" , "thirstyaffiliates-pro" ),
                                "Jewelry"            => __( "Jewelry" , "thirstyaffiliates-pro" ),
                                "KindleStore"        => __( "Kindle Store" , "thirstyaffiliates-pro" ),
                                "Kitchen"            => __( "Home & Kitchen" , "thirstyaffiliates-pro" ),
                                "Lighting"           => __( "Lighting" , "thirstyaffiliates-pro" ),
                                "Luggage"            => __( "Luggage" , "thirstyaffiliates-pro" ),
                                "Magazines"          => __( "Magazines" , "thirstyaffiliates-pro" ),
                                "Marketplace"        => __( "Marketplace" , "thirstyaffiliates-pro" ),
                                "MobileApps"         => __( "Apps & Games" , "thirstyaffiliates-pro" ),
                                "MP3Downloads"       => __( "Music Downloads" , "thirstyaffiliates-pro" ),
                                "Music"              => __( "Music CDs & Vinyl" , "thirstyaffiliates-pro" ),
                                "MusicalInstruments" => __( "Music Instruments & DJ Equipment" , "thirstyaffiliates-pro" ),
                                "OfficeProducts"     => __( "Office Supplies and Stationery" , "thirstyaffiliates-pro" ),
                                "Pantry"             => __( "Amazon Pantry" , "thirstyaffiliates-pro" ),
                                "PCHardware"         => __( "Computer Accessories" , "thirstyaffiliates-pro" ),
                                "PetSupplies"        => __( "Pet Supplies" , "thirstyaffiliates-pro" ),
                                "Photo"              => __( "Camera & Photo" , "thirstyaffiliates-pro" ),
                                "Shoes"              => __( "Shoes & Bags" , "thirstyaffiliates-pro" ),
                                "Software"           => __( "Software" , "thirstyaffiliates-pro" ),
                                "SportingGoods"      => __( "Sports & Outdoor" , "thirstyaffiliates-pro" ),
                                "Tools"              => __( "Hardware Tools" , "thirstyaffiliates-pro" ),
                                "Toys"               => __( "Games & Toys" , "thirstyaffiliates-pro" ),
                                "UnboxVideo"         => __( "Amazon Instant Video" , "thirstyaffiliates-pro" ),
                                "VideoGames"         => __( "Games" , "thirstyaffiliates-pro" ),
                                "Watches"            => __( "Watches" , "thirstyaffiliates-pro" )
                            ),
                    "ES" => array(
                                "All"                => __( "-- All Departments --" , "thirstyaffiliates-pro" ),
                                "Apparel"            => __( "Clothes and Accessories" , "thirstyaffiliates-pro" ),
                                "Automotive"         => __( "Car and Motorbike" , "thirstyaffiliates-pro" ),
                                "Baby"               => __( "Baby" , "thirstyaffiliates-pro" ),
                                "Beauty"             => __( "Beauty" , "thirstyaffiliates-pro" ),
                                "Books"              => __( "Books" , "thirstyaffiliates-pro" ),
                                "DVD"                => __( "Movies & TV" , "thirstyaffiliates-pro" ),
                                "Electronics"        => __( "Electronics" , "thirstyaffiliates-pro" ),
                                "ForeignBooks"       => __( "Foreign Books" , "thirstyaffiliates-pro" ),
                                "GiftCards"          => __( "Gift Vouchers" , "thirstyaffiliates-pro" ),
                                "Grocery"            => __( "Grocery" , "thirstyaffiliates-pro" ),
                                "Handmade"           => __( "Handmade" , "thirstyaffiliates-pro" ),
                                "HealthPersonalCare" => __( "Health and Personal Care" , "thirstyaffiliates-pro" ),
                                "Industrial"         => __( "Industry and Science" , "thirstyaffiliates-pro" ),
                                "Jewelry"            => __( "Jewelry" , "thirstyaffiliates-pro" ),
                                "KindleStore"        => __( "Kindle Store" , "thirstyaffiliates-pro" ),
                                "Kitchen"            => __( "Kitchen" , "thirstyaffiliates-pro" ),
                                "LawnAndGarden"      => __( "Garden" , "thirstyaffiliates-pro" ),
                                "Lighting"           => __( "Lighting" , "thirstyaffiliates-pro" ),
                                "Luggage"            => __( "Luggage" , "thirstyaffiliates-pro" ),
                                "MobileApps"         => __( "Apps and Games" , "thirstyaffiliates-pro" ),
                                "MP3Downloads"       => __( "Digital Music" , "thirstyaffiliates-pro" ),
                                "Music"              => __( "Music: CDs and DVDs" , "thirstyaffiliates-pro" ),
                                "MusicalInstruments" => __( "Musical Instruments" , "thirstyaffiliates-pro" ),
                                "OfficeProducts"     => __( "Office and Stationery" , "thirstyaffiliates-pro" ),
                                "PCHardware"         => __( "Computer" , "thirstyaffiliates-pro" ),
                                "Shoes"              => __( "Shoes & Bags" , "thirstyaffiliates-pro" ),
                                "Software"           => __( "Software" , "thirstyaffiliates-pro" ),
                                "SportingGoods"      => __( "Sports & Outdoors" , "thirstyaffiliates-pro" ),
                                "Tools"              => __( "DIY and Tools" , "thirstyaffiliates-pro" ),
                                "Toys"               => __( "Games & Toys" , "thirstyaffiliates-pro" ),
                                "VideoGames"         => __( "Video Games" , "thirstyaffiliates-pro" ),
                                "Watches"            => __( "Watches" , "thirstyaffiliates-pro" )
                            ),
                    "FR" => array(
                                "All"                => __( "-- All Departments --" , "thirstyaffiliates-pro" ),
                                "Apparel"            => __( "Clothes and Accessories" , "thirstyaffiliates-pro" ),
                                "Appliances"         => __( "Home Appliances" , "thirstyaffiliates-pro" ),
                                "Baby"               => __( "Baby & Toddler" , "thirstyaffiliates-pro" ),
                                "Beauty"             => __( "Beauty and Fragrance" , "thirstyaffiliates-pro" ),
                                "Blended"            => __( "Blended" , "thirstyaffiliates-pro" ),
                                "Books"              => __( "Books" , "thirstyaffiliates-pro" ),
                                "Classical"          => __( "Classical Music" , "thirstyaffiliates-pro" ),
                                "DVD"                => __( "DVD & Blu-ray" , "thirstyaffiliates-pro" ),
                                "Electronics"        => __( "Electronics" , "thirstyaffiliates-pro" ),
                                "ForeignBooks"       => __( "Foreign Books" , "thirstyaffiliates-pro" ),
                                "GiftCards"          => __( "Gift Cards" , "thirstyaffiliates-pro" ),
                                "Grocery"            => __( "Grocery" , "thirstyaffiliates-pro" ),
                                "Handmade"           => __( "Handmade" , "thirstyaffiliates-pro" ),
                                "HealthPersonalCare" => __( "Hygiene and Health" , "thirstyaffiliates-pro" ),
                                "HomeImprovement"    => __( "Home Improvement" , "thirstyaffiliates-pro" ),
                                "Industrial"         => __( "Industrial & Scientific" , "thirstyaffiliates-pro" ),
                                "Jewelry"            => __( "Jewelry" , "thirstyaffiliates-pro" ),
                                "KindleStore"        => __( "Kindle Store" , "thirstyaffiliates-pro" ),
                                "Kitchen"            => __( "Home & Kitchen" , "thirstyaffiliates-pro" ),
                                "LawnAndGarden"      => __( "Garden" , "thirstyaffiliates-pro" ),
                                "Lighting"           => __( "Lights & Lighting" , "thirstyaffiliates-pro" ),
                                "Luggage"            => __( "Luggage" , "thirstyaffiliates-pro" ),
                                "Marketplace"        => __( "Market Place" , "thirstyaffiliates-pro" ),
                                "MobileApps"         => __( "Apps & Games" , "thirstyaffiliates-pro" ),
                                "MP3Downloads"       => __( "Music Downloads" , "thirstyaffiliates-pro" ),
                                "Music"              => __( "Music: CD & Vinyl" , "thirstyaffiliates-pro" ),
                                "MusicalInstruments" => __( "Musical Instruments" , "thirstyaffiliates-pro" ),
                                "OfficeProducts"     => __( "Office Supplies" , "thirstyaffiliates-pro" ),
                                "PCHardware"         => __( "Computer" , "thirstyaffiliates-pro" ),
                                "PetSupplies"        => __( "Pet Supplies" , "thirstyaffiliates-pro" ),
                                "Shoes"              => __( "Shoes & Bags" , "thirstyaffiliates-pro" ),
                                "Software"           => __( "Software" , "thirstyaffiliates-pro" ),
                                "SportingGoods"      => __( "Sports and Outdoor" , "thirstyaffiliates-pro" ),
                                "Toys"               => __( "Games and Toys" , "thirstyaffiliates-pro" ),
                                "VideoGames"         => __( "Video Games" , "thirstyaffiliates-pro" ),
                                "Watches"            => __( "Watches " , "thirstyaffiliates-pro" )
                            ),
                    "IN" => array(
                                "All"                => __( "-- All Departments --" , "thirstyaffiliates-pro" ),
                                "Apparel"            => __( "Clothing & Accessories" , "thirstyaffiliates-pro" ),
                                "Appliances"         => __( "Appliances" , "thirstyaffiliates-pro" ),
                                "Automotive"         => __( "Car & Motorbike" , "thirstyaffiliates-pro" ),
                                "Baby"               => __( "Baby" , "thirstyaffiliates-pro" ),
                                "Beauty"             => __( "Beauty" , "thirstyaffiliates-pro" ),
                                "Books"              => __( "Books" , "thirstyaffiliates-pro" ),
                                "DVD"                => __( "Movies & TV Shows" , "thirstyaffiliates-pro" ),
                                "Electronics"        => __( "Electronics" , "thirstyaffiliates-pro" ),
                                "Furniture"          => __( "Furniture" , "thirstyaffiliates-pro" ),
                                "GiftCards"          => __( "Gift Cards" , "thirstyaffiliates-pro" ),
                                "Grocery"            => __( "Gourmet & Specialty Foods" , "thirstyaffiliates-pro" ),
                                "HealthPersonalCare" => __( "Health & Personal Care" , "thirstyaffiliates-pro" ),
                                "HomeGarden"         => __( "Home & Kitchen" , "thirstyaffiliates-pro" ),
                                "Industrial"         => __( "Industrial & Scientific" , "thirstyaffiliates-pro" ),
                                "Jewelry"            => __( "Jewelry" , "thirstyaffiliates-pro" ),
                                "KindleStore"        => __( "Kindle Store" , "thirstyaffiliates-pro" ),
                                "LawnAndGarden"      => __( "Lawn & Garden" , "thirstyaffiliates-pro" ),
                                "Luggage"            => __( "Luggage & Bags" , "thirstyaffiliates-pro" ),
                                "LuxuryBeauty"       => __( "Luxury Beauty" , "thirstyaffiliates-pro" ),
                                "Marketplace"        => __( "Marketplace" , "thirstyaffiliates-pro" ),
                                "Music"              => __( "Music" , "thirstyaffiliates-pro" ),
                                "MusicalInstruments" => __( "Musical Instruments" , "thirstyaffiliates-pro" ),
                                "OfficeProducts"     => __( "Office Products" , "thirstyaffiliates-pro" ),
                                "Pantry"             => __( "Amazon Pantry" , "thirstyaffiliates-pro" ),
                                "PCHardware"         => __( "Computers & Accessories" , "thirstyaffiliates-pro" ),
                                "PetSupplies"        => __( "Pet Supplies" , "thirstyaffiliates-pro" ),
                                "Shoes"              => __( "Shoes & Handbags" , "thirstyaffiliates-pro" ),
                                "Software"           => __( "Software" , "thirstyaffiliates-pro" ),
                                "SportingGoods"      => __( "Sports, Fitness & Outdoors" , "thirstyaffiliates-pro" ),
                                "Toys"               => __( "Toys & Games" , "thirstyaffiliates-pro" ),
                                "VideoGames"         => __( "Video Games" , "thirstyaffiliates-pro" ),
                                "Watches"            => __( "Watches" , "thirstyaffiliates-pro" )
                            ),
                    "IT" => array(
                                "All"                => __( "-- All Departments --" , "thirstyaffiliates-pro" ),
                                "Apparel"            => __( "Clothing" , "thirstyaffiliates-pro" ),
                                "Automotive"         => __( "Cars and Motorcycles" , "thirstyaffiliates-pro" ),
                                "Baby"               => __( "Baby & Maternity" , "thirstyaffiliates-pro" ),
                                "Beatury"            => __( "Beauty" , "thirstyaffiliates-pro" ),
                                "Books"              => __( "Books" , "thirstyaffiliates-pro" ),
                                "DVD"                => __( "Movies and TV" , "thirstyaffiliates-pro" ),
                                "Electronics"        => __( "Electronics" , "thirstyaffiliates-pro" ),
                                "ForeignBooks"       => __( "Foreign Books" , "thirstyaffiliates-pro" ),
                                "Garden"             => __( "Garden" , "thirstyaffiliates-pro" ),
                                "GiftCards"          => __( "Gift Vouchers" , "thirstyaffiliates-pro" ),
                                "Grocery"            => __( "Grocery" , "thirstyaffiliates-pro" ),
                                "Handmade"           => __( "Handmade" , "thirstyaffiliates-pro" ),
                                "HealthPersonalCare" => __( "Personal Care" , "thirstyaffiliates-pro" ),
                                "Industrial"         => __( "Industry and Science" , "thirstyaffiliates-pro" ),
                                "Jewelry"            => __( "Jewelry" , "thirstyaffiliates-pro" ),
                                "KindleStore"        => __( "Kindle Store" , "thirstyaffiliates-pro" ),
                                "Kitchen"            => __( "Home and Kitchen" , "thirstyaffiliates-pro" ),
                                "Lighting"           => __( "Lighting" , "thirstyaffiliates-pro" ),
                                "Luggage"            => __( "Luggage" , "thirstyaffiliates-pro" ),
                                "MobileApps"         => __( "App and Games" , "thirstyaffiliates-pro" ),
                                "MP3Downloads"       => __( "Digital Music" , "thirstyaffiliates-pro" ),
                                "Music"              => __( "CDs and Vinyls" , "thirstyaffiliates-pro" ),
                                "MusicalInstruments" => __( "Musical Instruments and DJs" , "thirstyaffiliates-pro" ),
                                "OfficeProducts"     => __( "Stationery and Office Products" , "thirstyaffiliates-pro" ),
                                "PCHardware"         => __( "Computer" , "thirstyaffiliates-pro" ),
                                "Shoes"              => __( "Shoes and Bags" , "thirstyaffiliates-pro" ),
                                "Software"           => __( "Software" , "thirstyaffiliates-pro" ),
                                "SportingGoods"      => __( "Sports & Outdoor" , "thirstyaffiliates-pro" ),
                                "Tools"              => __( "DIY Tools" , "thirstyaffiliates-pro" ),
                                "Toys"               => __( "Games and Toys" , "thirstyaffiliates-pro" ),
                                "VideoGames"         => __( "Video Games" , "thirstyaffiliates-pro" ),
                                "Watches"            => __( "Watches" , "thirstyaffiliates-pro" )
                            ),
                    "JP" => array(
                                "All"                => __( "-- All Departments --" , "thirstyaffiliates-pro" ),
                                "Apparel"            => __( "Clothing & Fashion Accessories" , "thirstyaffiliates-pro" ),
                                "Appliances"         => __( "Large household appliances" , "thirstyaffiliates-pro" ),
                                "Automotive"         => __( "Car / Motorcycle Supplies" , "thirstyaffiliates-pro" ),
                                "Baby"               => __( "Baby & Maternity" , "thirstyaffiliates-pro" ),
                                "Beauty"             => __( "Cosmetics" , "thirstyaffiliates-pro" ),
                                "Blended"            => __( "Blended" , "thirstyaffiliates-pro" ),
                                "Books"              => __( "Books" , "thirstyaffiliates-pro" ),
                                "Classical"          => __( "Classical" , "thirstyaffiliates-pro" ),
                                "CreditCards"        => __( "Credit Cards" , "thirstyaffiliates-pro" ),
                                "DVD"                => __( "DVD" , "thirstyaffiliates-pro" ),
                                "Electronics"        => __( "Home Appliances & Cameras" , "thirstyaffiliates-pro" ),
                                "ForeignBooks"       => __( "Foreign Books" , "thirstyaffiliates-pro" ),
                                "GiftCards"          => __( "Gift Vouchers" , "thirstyaffiliates-pro" ),
                                "Grocery"            => __( "Food · Beverages · Liquor" , "thirstyaffiliates-pro" ),
                                "HealthPersonalCare" => __( "Health & Beauty" , "thirstyaffiliates-pro" ),
                                "Hobbies"            => __( "Hobbies" , "thirstyaffiliates-pro" ),
                                "HomeImprovement"    => __( "DIY Tools" , "thirstyaffiliates-pro" ),
                                "Industrial"         => __( "Industry · Research and Development Products" , "thirstyaffiliates-pro" ),
                                "Jewelry"            => __( "Jewelry" , "thirstyaffiliates-pro" ),
                                "KindleStore"        => __( "Kindle Store" , "thirstyaffiliates-pro" ),
                                "Kitchen"            => __( "Home & Kitchen" , "thirstyaffiliates-pro" ),
                                "Marketplace"        => __( "Marketplace" , "thirstyaffiliates-pro" ),
                                "MobileApps"         => __( "Android Application" , "thirstyaffiliates-pro" ),
                                "MP3Downloads"       => __( "Digital Music" , "thirstyaffiliates-pro" ),
                                "Music"              => __( "Music" , "thirstyaffiliates-pro" ),
                                "MusicalInstruments" => __( "Musical Instruments" , "thirstyaffiliates-pro" ),
                                "OfficeProducts"     => __( "Stationary / Office Supplies" , "thirstyaffiliates-pro" ),
                                "PCHardware"         => __( "Computer Peripherals" , "thirstyaffiliates-pro" ),
                                "PetSupplies"        => __( "Pet Supplies" , "thirstyaffiliates-pro" ),
                                "Shoes"              => __( "Shoes & Bags" , "thirstyaffiliates-pro" ),
                                "Software"           => __( "PC Software" , "thirstyaffiliates-pro" ),
                                "SportingGoods"      => __( "Sports & Outdoor" , "thirstyaffiliates-pro" ),
                                "Toys"               => __( "Toys" , "thirstyaffiliates-pro" ),
                                "Video"              => __( "Video" , "thirstyaffiliates-pro" ),
                                "VideoDownload"      => __( "Amazon Instant Video" , "thirstyaffiliates-pro" ),
                                "VideoGames"         => __( "Video Games" , "thirstyaffiliates-pro" ),
                                "Watches"            => __( "Watches" , "thirstyaffiliates-pro" )
                            ),
                    "MX" => array(
                                "All"                => __( "-- All Departments --" , "thirstyaffiliats-pro" ),
                                "Baby"               => __( "Baby" , "thirstyaffiliats-pro" ),
                                "Books"              => __( "Books" , "thirstyaffiliats-pro" ),
                                "DVD"                => __( "DVD & Blu-ray" , "thirstyaffiliats-pro" ),
                                "Electronics"        => __( "Electronics & Photo" , "thirstyaffiliats-pro" ),
                                "HealthPersonalCare" => __( "Health & Personal Care" , "thirstyaffiliats-pro" ),
                                "HomeImprovement"    => __( "Tools and Home Improvement" , "thirstyaffiliats-pro" ),
                                "KindleStore"        => __( "Kindle Store" , "thirstyaffiliats-pro" ),
                                "Kitchen"            => __( "Home and Kitchen" , "thirstyaffiliats-pro" ),
                                "Music"              => __( "Music" , "thirstyaffiliats-pro" ),
                                "OfficeProducts"     => __( "Office & Stationery" , "thirstyaffiliats-pro" ),
                                "Software"           => __( "Software" , "thirstyaffiliats-pro" ),
                                "SportingGoods"      => __( "Sports and Outdoors" , "thirstyaffiliats-pro" ),
                                "VideoGames"         => __( "Video Games" , "thirstyaffiliats-pro" ),
                                "Watches"            => __( "Watches" , "thirstyaffiliats-pro" )
                            ),
                    "UK" => array(
                                "All"                => __( "-- All Departments --" , "thirstyaffiliates-pro" ),
                                "Apparel"            => __( "Clothing" , "thirstyaffiliates-pro" ),
                                "Appliances"         => __( "Large Appliances" , "thirstyaffiliates-pro" ),
                                "Automotive"         => __( "Car & Motorbike" , "thirstyaffiliates-pro" ),
                                "Baby"               => __( "Baby" , "thirstyaffiliates-pro" ),
                                "Beauty"             => __( "Beauty" , "thirstyaffiliates-pro" ),
                                "Blended"            => __( "Blended" , "thirstyaffiliates-pro" ),
                                "Books"              => __( "Books" , "thirstyaffiliates-pro" ),
                                "Classical"          => __( "Classical" , "thirstyaffiliates-pro" ),
                                "DVD"                => __( "DVD & Blu-ray" , "thirstyaffiliates-pro" ),
                                "Electronics"        => __( "Electronics & Photo" , "thirstyaffiliates-pro" ),
                                "GiftCards"          => __( "GiftCards" , "thirstyaffiliates-pro" ),
                                "Grocery"            => __( "Grocery" , "thirstyaffiliates-pro" ),
                                "Handmade"           => __( "Handmade" , "thirstyaffiliates-pro" ),
                                "HealthPersonalCare" => __( "Health & Personal Care" , "thirstyaffiliates-pro" ),
                                "HomeGarden"         => __( "Garden & Outdoors" , "thirstyaffiliates-pro" ),
                                "Industrial"         => __( "Industrial & Scientific" , "thirstyaffiliates-pro" ),
                                "Jewelry"            => __( "Jewelry" , "thirstyaffiliates-pro" ),
                                "KindleStore"        => __( "Kindle Store" , "thirstyaffiliates-pro" ),
                                "Kitchen"            => __( "Kitchen & Home" , "thirstyaffiliates-pro" ),
                                "Lighting"           => __( "Lighting" , "thirstyaffiliates-pro" ),
                                "Luggage"            => __( "Luggage" , "thirstyaffiliates-pro" ),
                                "Marketplace"        => __( "Marketplace" , "thirstyaffiliates-pro" ),
                                "MobileApps"         => __( "Apps & Games" , "thirstyaffiliates-pro" ),
                                "MP3Downloads"       => __( "Digital Music" , "thirstyaffiliates-pro" ),
                                "Music"              => __( "CDs & Vinyl" , "thirstyaffiliates-pro" ),
                                "MusicalInstruments" => __( "Musical Instruments & DJ" , "thirstyaffiliates-pro" ),
                                "OfficeProducts"     => __( "Stationery & Office Supplies" , "thirstyaffiliates-pro" ),
                                "Pantry"             => __( "Amazon Pantry" , "thirstyaffiliates-pro" ),
                                "PCHardware"         => __( "Computers" , "thirstyaffiliates-pro" ),
                                "PetSupplies"        => __( "Pet Supplies" , "thirstyaffiliates-pro" ),
                                "Shoes"              => __( "Shoes & Bags" , "thirstyaffiliates-pro" ),
                                "Software"           => __( "Software" , "thirstyaffiliates-pro" ),
                                "SportingGoods"      => __( "Sports & Outdoors" , "thirstyaffiliates-pro" ),
                                "Tools"              => __( "DIY & Tools" , "thirstyaffiliates-pro" ),
                                "Toys"               => __( "Toys & Games" , "thirstyaffiliates-pro" ),
                                "UnboxVideo"         => __( "Amazon Instant Video" , "thirstyaffiliates-pro" ),
                                "VHS"                => __( "VHS" , "thirstyaffiliates-pro" ),
                                "VideoGames"         => __( "PC & Video Games" , "thirstyaffiliates-pro" ),
                                "Watches"            => __( "Watches" , "thirstyaffiliates-pro" )
                            ),
                    "BR" => array(
                                "All"         => __( "-- All Departments --" , "thirstyaffiliats-pro" ),
                                "Books"       => __( "Books" , "thirstyaffiliats-pro" ),
                                "KindleStore" => __( "Kindle Store" , "thirstyaffiliats-pro" ),
                                "MobileApps"  => __( "Apps & Games" , "thirstyaffiliats-pro" )
                            )
                );

    }

    // Reference : http://docs.aws.amazon.com/AWSECommerceService/latest/DG/AnatomyOfaRESTRequest.html
    public function AMAZON_SEARCH_ENDPOINTS() {

        return array(
            "US" => "webservices.amazon.com",
            "CA" => "webservices.amazon.ca",
            "CN" => "webservices.amazon.cn",
            "DE" => "webservices.amazon.de",
            "ES" => "webservices.amazon.es",
            "FR" => "webservices.amazon.fr",
            "IN" => "webservices.amazon.in",
            "IT" => "webservices.amazon.it",
            "JP" => "webservices.amazon.co.jp",
            "MX" => "webservices.amazon.com.mx",
            "UK" => "webservices.amazon.co.uk",
            "BR" => "webservices.amazon.com.br"
        );

    }

    // Reference : http://docs.aws.amazon.com/AWSECommerceService/latest/DG/ErrorMessages.html
    public function AMAZON_API_CRITICAL_ERRORS() {

        return array(
            'MissingClientTokenId',
            'InvalidClientTokenId',
            'SignatureDoesNotMatch',
            // The first 3 above is not documented. I just found those out by testing
            'AWS.MissingParameters',
            'AWS.InternalError',
            'AWS.InvalidAccount',
            'AWS.InvalidAssociate',
            'AWS.InvalidOperationForMarketplace',
            'AWS.MissingOperationParameter',
            'AWS.MissingServiceParameter',
            'AWS.ECommerceService.NoExactMatches',
            'RequestThrottled',
        );

    }

    // HTAccess Module

    public function HTACCESS_FILE() {

        return ABSPATH . '/.htaccess';

    }

}
