<?php
function is_country_enabled($casinoID, $postType){

    $countryEnabledBonuses = @array_flip(get_post_meta($casinoID, 'casino_custom_meta_bonus_contries_filled', true));
    $restrictedCountriesISO = @array_flip(get_post_meta($casinoID, 'casino_custom_meta_rest_countries', true));
    $visitorsCountryISO = $GLOBALS['visitorsISO'];
    $noBonusOnthisCOuntry = get_post_meta($casinoID, $visitorsCountryISO.'casino_custom_meta_no_bonus', true);
    $localIso =  $GLOBALS['countryISO']; //Αν η χωρα ειναι ενεργοποιημε
    $bonusISO = get_bonus_iso($casinoID);
    $args = array();
    $args['restr'] = false;
    $args['noBonus'] = false;
    $args['ctaFunction'] = '';
    $args['aff_sc'] = get_post_meta($casinoID, 'casino_custom_meta_affiliate_link', true);
    $args['aff_re1'] = get_post_meta($casinoID, 'casino_custom_meta_affiliate_link_review', true);
    $args['aff_re2'] = get_post_meta($casinoID, 'casino_custom_meta_affiliate_link_review', true);
    $args['aff_bo'] = get_post_meta($casinoID, 'casino_custom_meta_affiliate_link_bonus', true);
    $args['aff_bo2'] = get_post_meta($casinoID, 'casino_custom_meta_affiliate_link_bonus', true);
    $args['aff_bo3'] = get_post_meta($casinoID, 'casino_custom_meta_affiliate_link_bonus', true);
    $args['flagStyle'] = '';
    $args['flagISO'] = $visitorsCountryISO;
    if((isset($countryEnabledBonuses[$visitorsCountryISO]) && !isset($restrictedCountriesISO[$visitorsCountryISO])) && $postType === "kss_casino"){ // Υπάρχει Bonus για την χώρα σου
        $args['isExclusive'] = get_post_meta($casinoID, $bonusISO."casino_custom_meta_exclusive", true);
        $args['ampExclusive'] = get_post_meta($casinoID, $bonusISO . "casino_custom_meta_exclusive", true) ? 'd-block' : 'd-none';
        $args['ISO'] = $visitorsCountryISO;
        $args['countryName'] = $GLOBALS['countryName'];
        $args['bonusCode'] = get_post_meta($casinoID, $bonusISO . "casino_custom_meta_bc_code", true) ?: 'No Code Required';
        $args['bonusText']['left-billboard'] = get_post_meta($casinoID, $bonusISO."casino_custom_meta_bonus_types", true);
        $args['bonusText']['cta-top'] = get_post_meta($casinoID, $bonusISO."casino_custom_meta_cta_for_top", true);
        $args['bonusText']['FlagText'] = get_post_meta($casinoID, $bonusISO."casino_custom_meta_cta_for_top_2", true);
//        $args['bonusText']['right-billboard'] = 'Ranked #'.get_rank_casino($casinoID).' in <a href="'.get_site_url().'/welcome-bonus/" target="_blank">Casino Bonuses</a> by Players in '.$GLOBALS['countryName'];
        $args['bonusText']['right-bonus'] = get_post_meta($casinoID, $bonusISO."casino_custom_meta_bonus_type", true);
        $args['bonusText']['min-dep'] = get_post_meta($casinoID, $bonusISO."casino_custom_meta_min_dep", true)?get_post_meta($casinoID, $bonusISO."casino_custom_meta_min_dep", true):'-';
        $args['bonusText']['terms'] = get_post_meta($casinoID, $bonusISO."casino_custom_meta_sp_terms", true);
        $args['bonusText']['right-percentage'] = get_post_meta($casinoID, $bonusISO."casino_custom_meta_bc_perc", true);
        $args['bonusText']['right-turnover-d'] =  get_post_meta($casinoID, $bonusISO."casino_custom_meta_wag_d", true);
        $args['bonusText']['right-turnover-b'] =  get_post_meta($casinoID, $bonusISO."casino_custom_meta_wag_b", true);
        $args['bonusText']['right-turnover-s'] = get_post_meta($casinoID, $bonusISO."casino_custom_meta_wag_s", true);
        $args['ctaText']['left-billboard'] = get_post_meta($casinoID, $bonusISO . "casino_custom_meta_top_up_cta", true) ?: 'Join Now';
        $args['ctaText']['center-billboard'] = $GLOBALS['countryISO'] === 'gb' ? 'Play' : 'Play Now';
        $args['ctaText']['right-billboard'] = 'Visit '.get_the_title($casinoID);
    }elseif((!isset($countryEnabledBonuses[$visitorsCountryISO]) && $noBonusOnthisCOuntry !== 1) && $postType === "kss_casino"){ // Δεν υπάρχει Bonus για την χώρα σου, δες το global
        $args['ISO'] = 'glb';
        $args['countryName'] = 'EU';
        $args['isExclusive'] = get_post_meta($casinoID, 'glbcasino_custom_meta_exclusive', true) ? true : false;
        $args['ampExclusive'] =get_post_meta($casinoID, "glbcasino_custom_meta_exclusive", true) ? 'd-block' : 'd-none';
        $args['bonusCode'] = get_post_meta($casinoID, $bonusISO . "casino_custom_meta_bc_code", true) ?: 'No Code Required';
        $args['bonusText']['left-billboard'] = get_post_meta($casinoID, $bonusISO."casino_custom_meta_bonus_types", true);
        $args['bonusText']['cta-top'] = get_post_meta($casinoID, "glbcasino_custom_meta_cta_for_top", true);
        $args['bonusText']['FlagText'] = get_post_meta($casinoID, "glbcasino_custom_meta_cta_for_top_2", true);
//        $args['bonusText']['right-billboard'] = 'Ranked #'.get_rank_casino($casinoID).' in <a href="'.get_site_url().'/welcome-bonus/" target="_blank">Casino Bonuses</a> by Players in '.$GLOBALS['countryName'];
        $args['bonusText']['right-bonus'] = get_post_meta($casinoID, "glbcasino_custom_meta_bonus_type", true);
        $args['bonusText']['min-dep'] = get_post_meta($casinoID, $bonusISO . "casino_custom_meta_min_dep", true) ?: '-';
        $args['bonusText']['terms'] = get_post_meta($casinoID, $bonusISO."casino_custom_meta_sp_terms", true);
        $args['bonusText']['right-percentage'] = get_post_meta($casinoID, "glbcasino_custom_meta_bc_perc", true);
        $args['bonusText']['right-turnover-d'] = get_post_meta($casinoID, "glbcasino_custom_meta_wag_d", true);
        $args['bonusText']['right-turnover-b'] = get_post_meta($casinoID, "glbcasino_custom_meta_wag_b", true);
        $args['bonusText']['right-turnover-s'] = get_post_meta($casinoID, "glbcasino_custom_meta_wag_s", true);
        $args['ctaText']['left-billboard'] = get_post_meta($casinoID, "glbcasino_custom_meta_top_up_cta", true) ?: 'Join Now';
        $args['ctaText']['center-billboard'] = $GLOBALS['countryISO'] === 'gb' ? 'Play' : 'Play Now';
        $args['ctaText']['right-billboard'] = 'Visit '.get_the_title($casinoID);
    }elseif((isset($countryEnabledBonuses[$visitorsCountryISO]) && !isset($restrictedCountriesISO[$visitorsCountryISO])) && $postType === "kss_casino"){
        $args['isExclusive'] = get_post_meta($casinoID, $bonusISO."casino_custom_meta_exclusive", true) ? true : false;
        $args['ampExclusive'] = get_post_meta($casinoID, $bonusISO . "casino_custom_meta_exclusive", true) ? 'd-block' : 'd-none';
        $args['ISO'] = $visitorsCountryISO;
        $args['countryName'] = $GLOBALS['countryName'];
        $args['bonusCode'] = get_post_meta($casinoID, $bonusISO . "casino_custom_meta_bc_code", true) ?: 'No Code Required';
        $args['bonusText']['left-billboard'] =  get_post_meta($casinoID, $bonusISO."casino_custom_meta_bonus_types", true);
        $args['bonusText']['FlagText'] = get_post_meta($casinoID, $bonusISO."casino_custom_meta_cta_for_top_2", true);
        $args['bonusText']['cta-top'] = get_post_meta($casinoID, $bonusISO."casino_custom_meta_cta_for_top", true);
//        $args['bonusText']['right-billboard'] = 'Ranked #'.get_rank_casino($casinoID).' in <a href="'.get_site_url().'/welcome-bonus/" target="_blank">Casino Bonuses</a> by Players in '.$GLOBALS['countryName'];
        $args['bonusText']['right-bonus'] =  get_post_meta($casinoID, $bonusISO."casino_custom_meta_bonus_type", true);
        $args['bonusText']['min-dep'] = get_post_meta($casinoID, $bonusISO . "casino_custom_meta_min_dep", true) ?: '-';
        $args['bonusText']['terms'] = get_post_meta($casinoID, $bonusISO."casino_custom_meta_sp_terms", true);
        $args['bonusText']['right-percentage'] =  get_post_meta($casinoID, $bonusISO."casino_custom_meta_bc_perc", true);
        $args['bonusText']['right-turnover-d'] =  get_post_meta($casinoID, $bonusISO."casino_custom_meta_wag_d", true);
        $args['bonusText']['right-turnover-b'] =  get_post_meta($casinoID, $bonusISO."casino_custom_meta_wag_b", true);
        $args['bonusText']['right-turnover-s'] =  get_post_meta($casinoID, $bonusISO."casino_custom_meta_wag_s", true);
        $args['ctaText']['left-billboard'] = get_post_meta($casinoID, $bonusISO."casino_custom_meta_top_up_cta", true) ?  get_post_meta($casinoID, $bonusISO."casino_custom_meta_top_up_cta", true) :  'Join Now';
        $args['ctaText']['center-billboard'] = $GLOBALS['countryISO'] === 'gb' ? 'Play' : 'Play Now';
        $args['ctaText']['right-billboard'] = 'Visit '.get_the_title($casinoID);
        $args['ctaText']['left-billboard-review'] = $GLOBALS['countryISO'] === 'gb' ? 'Join' : 'Join Now';
        $args['ctaText']['center-billboard-review'] = $GLOBALS['countryISO'] === 'gb' ? 'Play' : 'Play Now';
        $args['ctaText']['right-billboard-review'] = 'Visit '.get_the_title($casinoID);
    }elseif((!isset($countryEnabledBonuses[$visitorsCountryISO]) && !isset($restrictedCountriesISO[$visitorsCountryISO])) && $postType === "kss_casino"){
        $possibleNoBonus =  get_post_meta($casinoID, $visitorsCountryISO.'casino_custom_meta_no_bonus', true);
        $args['noBonus'] = $possibleNoBonus==1 ? true : false ;
        $args['isExclusive'] = get_post_meta($casinoID, "glbcasino_custom_meta_exclusive", true) ? true : false;
        $args['ampExclusive'] =get_post_meta($casinoID, "glbcasino_custom_meta_exclusive", true) ? 'd-block' : 'd-none';
        $args['ISO'] = 'glb';
        $args['countryName'] = $GLOBALS['countryName'];
        $args['bonusCode'] = get_post_meta($casinoID, "glbcasino_custom_meta_bc_code", true) ?: 'No Code Required';
        $args['bonusText']['left-billboard'] = $possibleNoBonus==1 ? '-' : get_post_meta($casinoID, $bonusISO."casino_custom_meta_bonus_types", true);
        $args['bonusText']['FlagText'] = get_post_meta($casinoID, "glbcasino_custom_meta_cta_for_top_2", true);
        $args['bonusText']['cta-top'] = get_post_meta($casinoID, "glbcasino_custom_meta_cta_for_top", true);
//        $args['bonusText']['right-billboard'] = 'Ranked #'.get_rank_casino($casinoID).' in <a href="'.get_site_url().'/welcome-bonus/" target="_blank">Casino Bonuses</a> by Players in '.$GLOBALS['countryName'];
        $args['bonusText']['right-bonus'] = $possibleNoBonus==1 ? '-' : get_post_meta($casinoID, $bonusISO."casino_custom_meta_bonus_type", true);
        $args['bonusText']['min-dep'] = $possibleNoBonus==1 ? '-' : get_post_meta($casinoID, $bonusISO."casino_custom_meta_min_dep", true);
        $args['bonusText']['terms'] = $possibleNoBonus==1 ? '-' : get_post_meta($casinoID, $bonusISO."casino_custom_meta_sp_terms", true);
        $args['bonusText']['right-percentage'] = $possibleNoBonus==1 ? '-' : get_post_meta($casinoID, $bonusISO."casino_custom_meta_bc_perc", true);
        $args['bonusText']['right-turnover-d'] = $possibleNoBonus==1 ? '-' : get_post_meta($casinoID, $bonusISO."casino_custom_meta_wag_d", true);
        $args['bonusText']['right-turnover-b'] = $possibleNoBonus==1 ? '-' : get_post_meta($casinoID, $bonusISO."casino_custom_meta_wag_b", true);
        $args['bonusText']['right-turnover-s'] = $possibleNoBonus==1 ? '-' : get_post_meta($casinoID, $bonusISO."casino_custom_meta_wag_s", true);
        $args['ctaText']['left-billboard'] = get_post_meta($casinoID, $bonusISO."casino_custom_meta_top_up_cta", true) ?  get_post_meta($casinoID, $bonusISO."casino_custom_meta_top_up_cta", true) :  'Join Now';
        $args['ctaText']['center-billboard'] = $GLOBALS['countryISO'] === 'gb' ? 'Play' : 'Play Now';
        $args['ctaText']['right-billboard'] = 'Visit '.get_the_title($casinoID);
        $args['ctaText']['left-billboard-review'] = $GLOBALS['countryISO'] === 'gb' ? 'Join' : 'Join Now';
        $args['ctaText']['center-billboard-review'] = $GLOBALS['countryISO'] === 'gb' ? 'Play' : 'Play Now';
        $args['ctaText']['right-billboard-review'] = 'Visit '.get_the_title($casinoID);
    }elseif(isset($restrictedCountriesISO[$visitorsCountryISO])){ // Η χώρα σου είναι restricted
        $args['isExclusive'] = false;
        $args['ampExclusive'] ='d-none';
        $args['ISO'] = $visitorsCountryISO;
        $args['bonusText']['FlagText'] = '';
        $args['bonusText']['cta-top'] = '';
        $args['countryName'] = $GLOBALS['countryName'];
        $args['restr'] = true;
        $args['noBonus'] = true;
        $args['ctaFunction'] = 'disabled';
        $args['flagStyle'] = 'disabled';
        $args['aff_sc'] = 'javascript:void(0)';
        $args['aff_re1'] = 'https://www.best50casino.com/online-casino-reviews/';
        $args['aff_re2'] = 'javascript:void(0)';
        $args['aff_bo'] = 'https://www.best50casino.com/welcome-bonus/';
        $args['aff_bo2'] = 'https://www.best50casino.com/online-casino-reviews/';
        $args['aff_bo3'] = 'javascript:void(0)';
//        $args['bonusText']['right-bonus'] = '<div class="disabled">-</div>';
//        $args['bonusText']['right-percentage'] = '<div class="disabled">-</div>';
//        $args['bonusText']['right-turnover-b'] = '<div class="disabled">-</div>';
//        $args['bonusText']['right-turnover-d'] = '<div class="disabled">-</div>';
//        $args['bonusText']['right-turnover-s'] = '<div class="disabled">-</div>';
        $args['bonusText']['right-bonus'] = '-';
        $args['bonusText']['right-percentage'] = '-';
        $args['bonusText']['right-turnover-b'] = '-';
        $args['bonusText']['right-turnover-d'] = '-';
        $args['bonusText']['right-turnover-s'] = '-';
        $args['bonusText']['min-dep'] = '-';
        $args['bonusText']['left-billboard'] = get_the_title($casinoID).' does not accept players from '.$GLOBALS['countryName'];
        $args['bonusText']['right-billboard'] = get_the_title($casinoID).' does not accept players from '.$GLOBALS['countryName'];
        $args['ctaText']['left-billboard'] = get_flags( '', '', $visitorsCountryISO, '20').' All bonuses';
        $args['ctaText']['center-billboard'] = 'Most Popular '.get_flags( '', '', $visitorsCountryISO, '20').' Casinos';
        $args['ctaText']['right-billboard'] = 'Visit '.get_the_title($casinoID);
        $args['ctaText']['left-billboard-review'] = 'All Casinos';
        $args['ctaText']['center-billboard-review'] = 'Most Popular Casinos';
        $args['ctaText']['right-billboard-review'] = 'Visit '.get_the_title($casinoID);
    }
    return $args;
}